# Generated by Django 3.2.4 on 2021-06-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('salary', models.IntegerField()),
                ('joining_date', models.DateField(auto_now=True)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
