# Generated by Django 3.2.3 on 2021-06-14 21:08

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[employee.models.name_check]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(validators=[employee.models.salary_check]),
        ),
    ]
